apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: smoke-test
spec:
  vertices:
    - name: in
      source:
        udsource:
          container:
            image: halfback-simulator:dev
            imagePullPolicy: Never
    - name: out
      sink:
        udsink:
          container:
            image: halfback-sink:dev
            imagePullPolicy: Never
            env:
              - name: CLICKHOUSE_HOST
                value: clickhouse:8123
              - name: CLICKHOUSE_PASSWORD
                value: halfback
  edges:
    - from: in
      to: out