apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: smoke-test
spec:
  vertices:
    - name: in
      source:
        udsource:
          container:
            image: halfback-simulator:dev
            imagePullPolicy: Never
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: out